### ISSUE TITLE
Roadmap to Alpha

### ISSUE THREAD

**Issue by vtambourine** [vtambourine/smstogo#1]
- [ ] Указать номер телефона для отправки
- [ ] Копирование текста в буфер обмена
- [ ] Сохранение значений полей между сессиями
- [ ] Приличный стиль страницы
